### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by Anurag30112003** [Arman-ali-khan-786/calculator#12]
![image](https://user-images.githubusercontent.com/79055093/193394668-8dfc94a5-0525-4d3a-bf77-7d294a8d9bd2.png)

**Comment by Arman-ali-khan-786** [comment]
> ![image](https://user-images.githubusercontent.com/79055093/193394668-8dfc94a5-0525-4d3a-bf77-7d294a8d9bd2.png)

if you wish you can work on it

**Comment by Anurag30112003** [comment]
assign me ..
