### ISSUE TITLE
making the size of the calculator smaller

### ISSUE THREAD

**Issue by dreymotoh** [Arman-ali-khan-786/calculator#16]
when i open the calculator on desktop there is space below on the calculator that needs to scroll down to see, would be awesome to have the full calculator in sight when entering the webpage

**Comment by Arman-ali-khan-786** [comment]
> when i open the calculator on desktop there is space below on the calculator that needs to scroll down to see, would be awesome to have the full calculator in sight when entering the webpage

yeah right

**Comment by dreymotoh** [comment]
can you assign this to me?

**Comment by dreymotoh** [comment]
?

**Comment by harshxtanwar** [comment]
can I get assigned to this issue please @Arman-ali-khan-786. I would love to work on it.

**Comment by Arman-ali-khan-786** [comment]
> can I get assigned to this issue please @Arman-ali-khan-786. I would love to work on it.

sorry this issue has been resolved
