### ISSUE TITLE
navbar is not showing in the deployment

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/calculator#17]
@itshypon  see to it

**Comment by Sarabjeet108** [comment]
Would like to work on this issue. Can you assign it to me?

**Comment by STBoyden** [comment]
![image](https://user-images.githubusercontent.com/25185976/193416998-3222f972-f0e8-434e-afb0-e9ffdb7d2391.png)

It seems as though GitHub pages is not deploying the new changes, which could be the reason for this. Maybe try a manual deployment? @Arman-ali-khan-786

**Comment by STBoyden** [comment]
Ah yes, it's stuck at commit b1b91d3de1e1cb37d7ae1338bff650d235fb589d rather than the latest commit b1b91d3de1e1cb37d7ae1338bff650d235fb589d

**Comment by itshypon** [comment]
@Arman-ali-khan-786 Yeah, it's stuck at old commit. Try updating it manually.

**Comment by Arman-ali-khan-786** [comment]
> ![image](https://user-images.githubusercontent.com/25185976/193416998-3222f972-f0e8-434e-afb0-e9ffdb7d2391.png)
> 
> It seems as though GitHub Pages is not deploying the new changes, which could be the reason for this. Maybe try a manual deployment? @Arman-ali-khan-786

yeah i see

**Comment by Arman-ali-khan-786** [comment]
@Sarabjeet108  this is has been taken care of
