### ISSUE TITLE
Button to all clear Calculator 

### ISSUE THREAD

**Issue by sidharthbh8** [Arman-ali-khan-786/calculator#33]
hey @Arman-ali-khan-786 I didn't saw any button to clear the whole calculations that we did
assign me this issue, I'll add this feature

**Comment by Arman-ali-khan-786** [comment]
> hey @Arman-ali-khan-786 I didn't saw any button to clear the whole calculations that we did assign me this issue, I'll add this feature

C button is there ,if I am not getting what you are trying to say then justify it properly okk

**Comment by sidharthbh8** [comment]
> > hey @Arman-ali-khan-786 I didn't saw any button to clear the whole calculations that we did assign me this issue, I'll add this feature
> 
> C button is there ,if I am not getting what you are trying to say then justify it properly okk

yeah my bad, didn't saw it first time
