### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by sidharthbh8** [Arman-ali-khan-786/calculator#34]
@Arman-ali-khan-786 I can add  a delete button which will delete the most recent number that user has added.
assign me this issue so I can add this feature 
and label this issue accordingly.

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786 I can add a delete button which will delete the most recent number that user has added. assign me this issue so I can add this feature and label this issue accordingly.

assigned
