### ISSUE TITLE
Need to add favicon

### ISSUE THREAD

**Issue by MohamedMafaz** [Arman-ali-khan-786/calculator#36]
Hi sir,
This project website don't have favicon. Please assign me this issue

**Comment by Arman-ali-khan-786** [comment]
> Hi sir, This project website don't have favicon. Please assign me this issue

go ahead

**Comment by Arman-ali-khan-786** [comment]
@MohamedMafaz are you still working on it??

**Comment by naikmubashir** [comment]
Assign me this issue. I would like to solve it

**Comment by naikmubashir** [comment]
Add Hacktoberfest tag, before merging my PR.
