### ISSUE TITLE
an option to save previous answer

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/calculator#4]

**Comment by Ilikepizza2** [comment]
Hello, can I work on this?

**Comment by Amarendra-ai** [comment]
I would like to work on this, please assign this to me

**Comment by abhi887449** [comment]
Hello @Arman-ali-khan-786 , I would like to work on this issue, please assign this to me

**Comment by Arman-ali-khan-786** [comment]
> Hello @Arman-ali-khan-786 , I would like to work on this issue, please assign this to me

assigned

**Comment by himanshu251001** [comment]
@Arman-ali-khan-786  assign me

**Comment by Arman-ali-khan-786** [comment]
@abhi887449 are you still on it??

**Comment by abhi887449** [comment]
> @abhi887449 are you still on it??

no

**Comment by NShreedesh** [comment]
Assign this to me please (I have done some work already)...
![image](https://user-images.githubusercontent.com/65639214/194710050-1fb6f015-6a62-41f4-ae0d-99c07bc152f4.png)
![image](https://user-images.githubusercontent.com/65639214/194710087-300f80f8-53df-49ed-b766-37de3dfef808.png)

**Comment by Arman-ali-khan-786** [comment]
> Assign this to me please (I have done some work already)... ![image](https://user-images.githubusercontent.com/65639214/194710050-1fb6f015-6a62-41f4-ae0d-99c07bc152f4.png) ![image](https://user-images.githubusercontent.com/65639214/194710087-300f80f8-53df-49ed-b766-37de3dfef808.png)

can you further specify what changes will you do ?? by the way be specific on the issue ok

**Comment by NShreedesh** [comment]
> > Assign this to me please (I have done some work already)... ![image](https://user-images.githubusercontent.com/65639214/194710050-1fb6f015-6a62-41f4-ae0d-99c07bc152f4.png) ![image](https://user-images.githubusercontent.com/65639214/194710087-300f80f8-53df-49ed-b766-37de3dfef808.png)
> 
> can you further specify what changes will you do ?? by the way be specific on the issue ok


you can see in the above image, below the answer there is a new text to show the saved answer.
the answer will be saved and will be displayed in the previous answer section the next time.
