### ISSUE TITLE
need a proper documentation of contribution.md 

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/calculator#6]

**Comment by Akshu-on-github** [comment]
Hello there! I'd like to work on this issue - I can start working on it upon assignment

**Comment by itshypon** [comment]
Hi, I would like to work on this issue. Thanks !

**Comment by akshatjain1004** [comment]
Hi this is Akshat Jain and I'd like to work on this issue. From what I've understood, you want  meto write a markdown explaining various guidelines for contributors. I'd like to complete it within a given time frame :)

**Comment by Arman-ali-khan-786** [comment]
> Hi this is Akshat Jain and I'd like to work on this issue. From what I've understood, you want meto write a markdown explaining various guidelines for contributors. I'd like to complete it within a given time frame :)

i want it by 2nd oct ok !!

**Comment by akshatjain1004** [comment]
> > Hi this is Akshat Jain and I'd like to work on this issue. From what I've understood, you want meto write a markdown explaining various guidelines for contributors. I'd like to complete it within a given time frame :)
> 
> i want it by 2nd oct ok !!

sure! Thanks for the issue :)
